name: Node lint
run-name: Lint nodejs app
on: [push]

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
          npm install

      - name: Ejecutar linter
        working-directory: ./calculadora
        run: |
          npm run lint
